/*
 * ZZ9000AX qualified fixed-point audio conversion core.
 *
 * One integer-only polyphase kernel serves every conversion site: the AHI
 * per-period playback path, the SDK pump (stream and media bindings), and
 * the capture receive conversion. Coefficients are committed const tables
 * generated by util/gen_audio_convert_tables.py (Q14 unity-DC phases,
 * exact-rational stepping); no floating point anywhere, so the same code
 * runs host-side in test/audio and target-side in the ISRs.
 *
 * Copyright (C) 2026, Dimitris Panokostas <midwan@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef ZZ_AUDIO_CONVERT_H
#define ZZ_AUDIO_CONVERT_H

#include <stdint.h>

#include "audio_convert_tables.h"

/* Coefficients are Q14 unity-DC (tap sum 16384): accumulate in int32,
 * add half an output LSB, arithmetic shift right by 14, saturate to int16. */
#define ZZ_AUDIO_CONVERT_SHIFT 14

/* Largest generated branch (48 kHz -> 8 kHz capture: 603 taps). */
#define ZZ_AUDIO_CONVERT_MAX_TAPS 604

/* Frames of input history a private instance carries across calls. */
#define ZZ_AUDIO_CONVERT_HISTORY (ZZ_AUDIO_CONVERT_MAX_TAPS - 1)

struct zz_audio_convert {
	const struct zz_audio_convert_ratio *ratio; /* NULL: passthrough */
	uint32_t pos_int;  /* input frames before next output's base */
	uint32_t pos_frac; /* exact-rational phase, 0 .. step_den-1 */
	uint32_t clips;    /* saturating writes since init */
	uint16_t history_len; /* valid frames in history (warmup) */
	int16_t history[2][ZZ_AUDIO_CONVERT_HISTORY];
};

/*
 * Select the coefficient bank for an in_rate -> out_rate pair.
 * Returns 0 for a converting pair, 1 when the pair is an identity or an
 * unsupported off-table ratio (ctx->ratio stays NULL: byte-exact
 * passthrough, matching the capture register contract's six-count rule),
 * or -1 for invalid arguments. Always resets the instance.
 */
int zz_audio_convert_init(struct zz_audio_convert *ctx, uint32_t in_rate,
                          uint32_t out_rate);

/*
 * Clear phase, history, and clip count together. Reset is one atomic
 * event: partial resets click and jump pitch. Does not change the
 * selected ratio.
 */
void zz_audio_convert_reset(struct zz_audio_convert *ctx);

/*
 * Convert in_frames interleaved stereo frames to out_frames frames.
 * The caller guarantees the exact per-period pair (rate/50 and 960 for
 * playback; 960 and the advertised count for capture); consumption and
 * production are exact, phase carries, and the rational position lands
 * on the call boundary so successive calls chain without drift.
 * In identity mode frames are copied verbatim. Sites own mono
 * duplication (duplicate-before-convert, one phase clock per frame) and
 * byte-order handling around this call.
 */
void zz_audio_convert_stream(struct zz_audio_convert *ctx,
                             const int16_t *in, int16_t *out,
                             uint16_t in_frames, uint16_t out_frames);

static inline uint32_t zz_audio_convert_clips(
    const struct zz_audio_convert *ctx)
{
	return ctx->clips;
}

#endif /* ZZ_AUDIO_CONVERT_H */
