/*
 * Generated by util/gen_audio_convert_tables.py -- DO NOT EDIT.
 *
 * Regenerate with: python util/gen_audio_convert_tables.py
 * Design: Kaiser windowed-sinc polyphase FIR, A = 80 dB,
 *         passband edge 0.45 * min(fs_in, fs_out), stopband edge
 *         min(fs_in, fs_out) - passband edge, causal delayed-symmetric
 *         kernel, exact-rational phase stepping, unity DC gain per phase
 *         (Q14 tap sum == 16384, runtime round-shift 16), per-phase L1 <= 48000.
 */

#ifndef ZZ_AUDIO_CONVERT_TABLES_H
#define ZZ_AUDIO_CONVERT_TABLES_H

#include <stdint.h>

/* One conversion direction: exact-rational step q/p =
 * in_rate/out_rate (reduced). Output n uses input base
 * (n*q)/p and phase (n*q)%p; y[n] = sum_k coefs[phase][k] *
 * x[base - k]. group_delay is in input samples.
 */
struct zz_audio_convert_ratio {
	uint16_t phases;
	uint16_t taps;
	uint16_t step_int;
	uint16_t step_num;
	uint16_t step_den;
	uint16_t group_delay;
	const int16_t *const *coefs;
};

extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_8000_48000; /* 8000 -> 48000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_12000_48000; /* 12000 -> 48000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_24000_48000; /* 24000 -> 48000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_32000_48000; /* 32000 -> 48000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_44100_48000; /* 44100 -> 48000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_48000_8000; /* 48000 -> 8000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_48000_12000; /* 48000 -> 12000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_48000_24000; /* 48000 -> 24000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_48000_32000; /* 48000 -> 32000 Hz */
extern const struct zz_audio_convert_ratio zz_audio_convert_ratio_48000_44100; /* 48000 -> 44100 Hz */

#endif /* ZZ_AUDIO_CONVERT_TABLES_H */
