#!/bin/bash
#
# Package BOOT.bin from the committed boot inputs.
#
# Inputs:
#   bootimage_work/FSBL_exec.elf              (committed)
#   bootimage_work/zz9000_ps_wrapper.bit      (committed or rebuilt by build_bitstream.sh)
#   ZZ9000_proto.sdk/ZZ9000OS/build/ZZ9000OS.elf  (rebuilt by build_firmware.sh)
#
# Output: bootimage_work/BOOT.bin, unless --output is given
#
# Bootgen discovery order:
#   1. $BOOTGEN (explicit override)
#   2. bootgen on PATH
#   3. /Users/midwan/Gitlab/bootgen/bootgen (Mac default — adjust if you moved it)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

usage() {
    cat >&2 <<'EOF'
Usage: ./build_bootimage.sh [--bitstream PATH] [--output PATH]

Options:
  --bitstream PATH   FPGA bitstream to package
                     (default: bootimage_work/zz9000_ps_wrapper.bit)
  --output PATH      BOOT.bin output path
                     (default: bootimage_work/BOOT.bin)
EOF
}

BITSTREAM=bootimage_work/zz9000_ps_wrapper.bit
OUTPUT=bootimage_work/BOOT.bin

while [ "$#" -gt 0 ]; do
    case "$1" in
        --bitstream)
            if [ "$#" -lt 2 ]; then
                echo "ERROR: --bitstream needs a path." >&2
                usage
                exit 1
            fi
            BITSTREAM=$2
            shift 2
            ;;
        --output)
            if [ "$#" -lt 2 ]; then
                echo "ERROR: --output needs a path." >&2
                usage
                exit 1
            fi
            OUTPUT=$2
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "ERROR: unknown argument: $1" >&2
            usage
            exit 1
            ;;
    esac
done

# Locate bootgen. In-tree bootgen/ is the usual build location from the
# sibling bootgen repo; fall back to an older out-of-tree spot for
# historical macOS setups.
if [ -n "${BOOTGEN:-}" ]; then
    : # use explicit override
elif command -v bootgen >/dev/null 2>&1; then
    BOOTGEN=$(command -v bootgen)
elif [ -x "$SCRIPT_DIR/bootgen/bootgen" ]; then
    BOOTGEN="$SCRIPT_DIR/bootgen/bootgen"
elif [ -x /Users/midwan/Gitlab/bootgen/bootgen ]; then
    BOOTGEN=/Users/midwan/Gitlab/bootgen/bootgen
else
    echo "ERROR: bootgen not found." >&2
    echo "  Set BOOTGEN=/path/to/bootgen, install it on PATH, or build from" >&2
    echo "  https://github.com/Xilinx/bootgen and place the binary somewhere reachable." >&2
    exit 1
fi

# Sanity-check required inputs exist.
required=(
    bootimage_work/FSBL_exec.elf
    "$BITSTREAM"
    ZZ9000_proto.sdk/ZZ9000OS/build/ZZ9000OS.elf
)
for f in "${required[@]}"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: missing required input: $f" >&2
        if [ "$f" = "ZZ9000_proto.sdk/ZZ9000OS/build/ZZ9000OS.elf" ]; then
            echo "  Run ./build_firmware.sh first." >&2
        fi
        exit 1
    fi
done

echo "[bootimage] bootgen: $BOOTGEN"
echo "[bootimage] bitstream: $BITSTREAM"
echo "[bootimage] output:    $OUTPUT"

mkdir -p "$(dirname "$OUTPUT")"
TMP_BIF=$(mktemp "${TMPDIR:-/tmp}/zz9000-bootimage.XXXXXX.bif")
trap 'rm -f "$TMP_BIF"' EXIT

cat > "$TMP_BIF" <<EOF
// Generated by build_bootimage.sh.
the_ROM_image:
{
  [bootloader] bootimage_work/FSBL_exec.elf
  $BITSTREAM
  ZZ9000_proto.sdk/ZZ9000OS/build/ZZ9000OS.elf
}
EOF

rm -f "$OUTPUT"
"$BOOTGEN" -arch zynq -image "$TMP_BIF" -w on -o "$OUTPUT"

ls -lh "$OUTPUT"
echo "[bootimage] done: $OUTPUT"
