#!/bin/bash
# Copyright (C) 2026, Dimitris Panokostas <midwan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Build a decoder-only libFLAC static archive for ZZ9000OS (U7 native FLAC).
# The pinned release tarball and every derived file stay below build/deps; no
# upstream source is vendored into the repository. The upstream BSD-3-Clause
# notice (COPYING.Xiph, "Xiph.org BSD-like license" per the release README)
# covering libFLAC is checked in under ZZ9000_proto.sdk/ZZ9000OS/src/flac/.
#
# Only the stream-decoder translation units are compiled: no encoder
# (stream_encoder*, bitwriter, window), no Ogg (built with FLAC__HAS_OGG=0,
# ogg_* units excluded), no metadata editing (metadata_iterators,
# metadata_object), no programs, examples, libFLAC++ or x86/NEON intrinsics.
# Every malloc/calloc/realloc/free inside libFLAC is routed through
# src/sdk_flac_alloc.h so firmware allocations are quota-bounded and
# registered with the core-1 decode tracker.

set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
OS_DIR="$SCRIPT_DIR/ZZ9000_proto.sdk/ZZ9000OS"
VERSION="${LIBFLAC_VERSION:-1.5.0}"
# Release 1.5.0 (2025-02-11); hash taken from the GitHub release asset.
SHA256="${LIBFLAC_SHA256:-f2c1c76592a82ffff8413ba3c4a1299b6c7ab06c734dee03fd88630485c2b920}"
URL="${LIBFLAC_URL:-https://github.com/xiph/flac/releases/download/${VERSION}/flac-${VERSION}.tar.xz}"
TARGET="${LIBFLAC_TARGET:-arm}"

usage() {
    cat <<'EOF'
Usage: build_flac.sh [--host|--arm]

Build the pinned decoder-only libFLAC archive (libflacdec.a). The default
target is ARM firmware; --host builds a native archive for the host tests.
EOF
}

case "$#" in
    0) ;;
    1)
        case "$1" in
            --host) TARGET=host ;;
            --arm) TARGET=arm ;;
            --help|-h) usage; exit 0 ;;
            *) usage >&2; exit 2 ;;
        esac ;;
    *) usage >&2; exit 2 ;;
esac
case "$TARGET" in
    arm|host) ;;
    *) echo "ERROR: LIBFLAC_TARGET must be arm or host." >&2; exit 2 ;;
esac

ALLOC_HEADER="$OS_DIR/src/sdk_flac_alloc.h"
if [ ! -f "$ALLOC_HEADER" ]; then
    echo "ERROR: missing $ALLOC_HEADER" >&2
    exit 1
fi

DEPS_DIR="$OS_DIR/build/deps/flac/$VERSION"
ARCHIVE="$DEPS_DIR/flac-$VERSION.tar.xz"
SRC_DIR="$DEPS_DIR/src"
OUT_DIR="$DEPS_DIR/$TARGET"
LIB="$OUT_DIR/libflacdec.a"

mkdir -p "$DEPS_DIR"
if [ ! -f "$ARCHIVE" ]; then
    echo "[libFLAC] downloading $URL"
    if command -v curl >/dev/null 2>&1; then
        curl --fail --location --silent --show-error "$URL" -o "$ARCHIVE"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$URL" -O "$ARCHIVE"
    else
        echo "ERROR: install curl or wget to download libFLAC." >&2
        exit 1
    fi
fi
if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL="$(sha256sum "$ARCHIVE" | awk '{print $1}')"
else
    ACTUAL="$(shasum -a 256 "$ARCHIVE" | awk '{print $1}')"
fi
if [ "$ACTUAL" != "$SHA256" ]; then
    echo "ERROR: libFLAC archive checksum mismatch." >&2
    echo "  expected: $SHA256" >&2
    echo "  actual:   $ACTUAL" >&2
    rm -f "$ARCHIVE"
    exit 1
fi
if [ ! -f "$SRC_DIR/src/libFLAC/stream_decoder.c" ]; then
    rm -rf "$SRC_DIR"
    mkdir -p "$SRC_DIR"
    tar xJf "$ARCHIVE" --strip-components=1 -C "$SRC_DIR"
fi

if [ "$TARGET" = arm ]; then
    : "${ARM_NONE_EABI_CC:=arm-none-eabi-gcc}"
    : "${ARM_NONE_EABI_AR:=arm-none-eabi-ar}"
    : "${ARM_NONE_EABI_RANLIB:=arm-none-eabi-ranlib}"
    CC_TOOL="$ARM_NONE_EABI_CC"; AR_TOOL="$ARM_NONE_EABI_AR"; RANLIB_TOOL="$ARM_NONE_EABI_RANLIB"
    CFLAGS_TARGET="-mcpu=cortex-a9 -marm -mfpu=neon -mfloat-abi=hard \
-O2 -ffunction-sections -fdata-sections -fno-unwind-tables \
-fno-asynchronous-unwind-tables -fno-strict-aliasing"
else
    : "${CC_FOR_BUILD:=cc}"
    : "${AR_FOR_BUILD:=ar}"
    : "${RANLIB_FOR_BUILD:=ranlib}"
    CC_TOOL="$CC_FOR_BUILD"; AR_TOOL="$AR_FOR_BUILD"; RANLIB_TOOL="$RANLIB_FOR_BUILD"
    CFLAGS_TARGET="-O2 -ffunction-sections -fdata-sections -fno-strict-aliasing"
fi
for tool in "$CC_TOOL" "$AR_TOOL" "$RANLIB_TOOL"; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "ERROR: required tool not found: $tool" >&2; exit 1; }
done

# Rebuild whenever the allocator shim or this recipe changed.
STAMP_INPUT="$(cat "$ALLOC_HEADER" "$0" | cksum | awk '{print $1}')"
if [ -f "$LIB" ] && [ -f "$OUT_DIR/.stamp" ] &&
   [ "$(cat "$OUT_DIR/.stamp")" = "$STAMP_INPUT" ]; then
    touch "$LIB"
    echo "[libFLAC] up to date ($TARGET): $LIB"
    exit 0
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/obj" "$OUT_DIR/config" "$OUT_DIR/include/FLAC"
# Hand-written configuration: portable C, integer-only decode path, no Ogg,
# no assembly, 32-bit bitreader words, no stdio seek extensions.
cat > "$OUT_DIR/config/config.h" <<'EOF'
/* Generated by build_flac.sh - decoder-only libFLAC configuration. */
#define CPU_IS_BIG_ENDIAN 0
#define WORDS_BIGENDIAN 0
#define ENABLE_64_BIT_WORDS 0
#define FLAC__HAS_OGG 0
#define OGG_FOUND 0
#define FLAC__HAS_X86INTRIN 0
#define FLAC__HAS_NEONINTRIN 0
#define FLAC__HAS_A64NEONINTRIN 0
#define FLAC__NO_ASM 1
#define FLAC__INTEGER_ONLY_LIBRARY 1
#define HAVE_STDINT_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LROUND 1
#define PACKAGE_VERSION "1.5.0"
EOF

# float.c supplies the fixed-point helpers fixed.c references under
# FLAC__INTEGER_ONLY_LIBRARY; no floating-point decode code is compiled.
DECODER_TUS="bitmath bitreader cpu crc fixed float format lpc md5 memory stream_decoder"
for tu in $DECODER_TUS; do
    "$CC_TOOL" $CFLAGS_TARGET -DHAVE_CONFIG_H -DNDEBUG -DFLAC__NO_DLL \
        -DSDK_FLAC_REPLACE_ALLOCATORS -include "$ALLOC_HEADER" \
        -I"$OUT_DIR/config" -I"$SRC_DIR/include" \
        -I"$SRC_DIR/src/libFLAC/include" \
        -c "$SRC_DIR/src/libFLAC/$tu.c" -o "$OUT_DIR/obj/$tu.o"
done
"$AR_TOOL" rcs "$LIB" "$OUT_DIR"/obj/*.o
"$RANLIB_TOOL" "$LIB"
for hdr in all.h assert.h callback.h export.h format.h metadata.h ordinals.h \
           stream_decoder.h; do
    cp "$SRC_DIR/include/FLAC/$hdr" "$OUT_DIR/include/FLAC/$hdr"
done
rm -rf "$OUT_DIR/obj"
printf '%s\n' "$STAMP_INPUT" > "$OUT_DIR/.stamp"
echo "[libFLAC] built ($TARGET): $LIB"
