#!/usr/bin/env python3
# Copyright (C) 2026, Dimitris Panokostas <midwan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generate compact, deterministic DVD MPEG-PS/VOB test fixtures for U11:
# - PAL 720x576 25p with MP2 stereo audio
# - PAL 720x576 TFF interlaced with AC-3 stereo audio
# - NTSC 720x480 30000/1001 with DVD LPCM stereo audio
# - NTSC film 720x480 24000/1001 with signaled 3:2 repeat-first-field cadence
# - 5.1 multichannel AC-3 DVD VOB for deterministic stereo downmix verification
# - DVD LPCM packets with exact known 16-bit mono and stereo patterns
# - 2 s of AC-3 2.0 192 kbit/s in 2 KB DVD packs (about 2.6 AC-3 frames per
#   pack), so every frame must be decoded without the stage backing up
# - two AC-3 tracks (substreams 0x80 and 0x81) of different lengths, so a
#   demux that merges substreams is visible in the decoded frame count
#
# Generator: FFmpeg 7.1.5-0+deb13u1 (built with gcc 14) + Python 3.13
# "generate_dvd_fixtures.py ac3_tracks" regenerates only the two AC-3 track
# fixtures and leaves the others byte-identical.

import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))

def write_c_include(path, symbol_name, data):
    with open(path, "w") as f:
        f.write("/* Generated by generate_dvd_fixtures.py. */\n")
        f.write(f"static const uint8_t {symbol_name}[] = {{\n")
        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"  {hex_str},\n")
        f.write("};\n")
        f.write(f"static const uint32_t {symbol_name}_len = {len(data)}U;\n")
    print(f"Wrote {path} ({len(data)} bytes)")

def build_fixtures():
    with tempfile.TemporaryDirectory() as tmpdir:
        # 1. PAL 720x576 25p + MP2 audio
        pal_25p_vob = os.path.join(tmpdir, "pal_25p.vob")
        cmd_pal_25p = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=720x576:rate=25:duration=0.2",
            "-f", "lavfi", "-i", "sine=frequency=1000:sample_rate=48000:duration=0.2",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "6", "-b:v", "3000k",
            "-c:a", "mp2", "-b:a", "192k", "-ar", "48000", "-ac", "2",
            "-f", "dvd", pal_25p_vob
        ]
        subprocess.run(cmd_pal_25p, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_pal_25p_fixture.inc"),
            "zz9k_dvd_pal_25p_fixture",
            open(pal_25p_vob, "rb").read()
        )

        # 2. PAL 720x576 TFF interlaced + AC-3 stereo
        pal_tff_vob = os.path.join(tmpdir, "pal_tff.vob")
        cmd_pal_tff = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=720x576:rate=25:duration=0.2",
            "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=0.2",
            "-vf", "setfield=tff", "-flags", "+ildct+ilme",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "6", "-b:v", "3000k",
            "-c:a", "ac3", "-b:a", "192k", "-ar", "48000", "-ac", "2",
            "-f", "dvd", pal_tff_vob
        ]
        subprocess.run(cmd_pal_tff, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_pal_tff_fixture.inc"),
            "zz9k_dvd_pal_tff_fixture",
            open(pal_tff_vob, "rb").read()
        )

        # 3. NTSC 720x480 30000/1001 + DVD LPCM stereo
        ntsc_30_vob = os.path.join(tmpdir, "ntsc_30.vob")
        cmd_ntsc_30 = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=720x480:rate=30000/1001:duration=0.2",
            "-f", "lavfi", "-i", "sine=frequency=880:sample_rate=48000:duration=0.2",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "6", "-b:v", "3000k",
            "-c:a", "pcm_dvd", "-ar", "48000", "-ac", "2",
            "-f", "dvd", ntsc_30_vob
        ]
        subprocess.run(cmd_ntsc_30, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_ntsc_30_fixture.inc"),
            "zz9k_dvd_ntsc_30_fixture",
            open(ntsc_30_vob, "rb").read()
        )

        # 4. NTSC film 24000/1001 with 3:2 cadence (signaled repeat_first_field)
        ntsc_film_raw = os.path.join(tmpdir, "ntsc_film_raw.vob")
        cmd_ntsc_film = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "testsrc=size=720x480:rate=24000/1001:duration=0.25",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "6", "-b:v", "3000k",
            "-f", "dvd", ntsc_film_raw
        ]
        subprocess.run(cmd_ntsc_film, check=True)
        film_bytes = bytearray(open(ntsc_film_raw, "rb").read())
        pos = 0
        pic_idx = 0
        while True:
            idx = film_bytes.find(b"\x00\x00\x01\xb5", pos)
            if idx == -1:
                break
            ext_id = film_bytes[idx+4] >> 4
            if ext_id == 1: # sequence extension
                # Clear progressive_sequence (bit 3 of byte 1, i.e. film_bytes[idx+5] & ~0x08)
                film_bytes[idx+5] &= ~0x08
            elif ext_id == 8: # picture coding extension
                b3 = film_bytes[idx+7]
                # Alternate repeat_first_field: frame 0 (2 fields), frame 1 (3 fields)...
                if pic_idx % 2 == 1:
                    b3 = (b3 | 0x82) # top_field_first + repeat_first_field
                else:
                    b3 = (b3 | 0x80) & ~0x02 # top_field_first, no repeat
                film_bytes[idx+7] = b3
                pic_idx += 1
            pos = idx + 4
        write_c_include(
            os.path.join(HERE, "dvd_ntsc_film_32_fixture.inc"),
            "zz9k_dvd_ntsc_film_32_fixture",
            film_bytes
        )

        # 5. 5.1 Multichannel AC-3 DVD VOB for deterministic stereo downmix
        ac3_51_vob = os.path.join(tmpdir, "ac3_51.vob")
        cmd_ac3_51 = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=0.1",
            "-ac", "6", "-c:a", "ac3", "-b:a", "448k",
            "-f", "dvd", ac3_51_vob
        ]
        subprocess.run(cmd_ac3_51, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_ac3_51_fixture.inc"),
            "zz9k_dvd_ac3_51_fixture",
            open(ac3_51_vob, "rb").read()
        )

def build_ac3_track_fixtures():
    with tempfile.TemporaryDirectory() as tmpdir:
        # 6. 2 s AC-3 2.0 192 kbit/s (768-byte frames) behind a still video
        ac3_192_vob = os.path.join(tmpdir, "ac3_192.vob")
        cmd_ac3_192 = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "color=c=gray:size=352x288:rate=25:duration=2",
            "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=2",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "12", "-b:v", "300k",
            "-c:a", "ac3", "-b:a", "192k", "-ar", "48000", "-ac", "2",
            "-f", "dvd", ac3_192_vob
        ]
        subprocess.run(cmd_ac3_192, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_ac3_192_fixture.inc"),
            "zz9k_dvd_ac3_192_fixture",
            open(ac3_192_vob, "rb").read()
        )

        # 7. Two AC-3 tracks: 0x80 = 0.2 s at 440 Hz, 0x81 = 0.6 s at 1 kHz
        ac3_dual_vob = os.path.join(tmpdir, "ac3_dual.vob")
        cmd_ac3_dual = [
            "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
            "-f", "lavfi", "-i", "color=c=gray:size=352x288:rate=25:duration=0.6",
            "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000:duration=0.2",
            "-f", "lavfi", "-i", "sine=frequency=1000:sample_rate=48000:duration=0.6",
            "-map", "0:v", "-map", "1:a", "-map", "2:a",
            "-c:v", "mpeg2video", "-pix_fmt", "yuv420p", "-g", "12", "-b:v", "300k",
            "-c:a", "ac3", "-b:a", "192k", "-ar", "48000", "-ac", "2",
            "-f", "dvd", ac3_dual_vob
        ]
        subprocess.run(cmd_ac3_dual, check=True)
        write_c_include(
            os.path.join(HERE, "dvd_ac3_dual_fixture.inc"),
            "zz9k_dvd_ac3_dual_fixture",
            open(ac3_dual_vob, "rb").read()
        )

if __name__ == "__main__":
    if sys.argv[1:] == ["ac3_tracks"]:
        build_ac3_track_fixtures()
    else:
        build_fixtures()
        build_ac3_track_fixtures()
