# Rebuild the compact MPEG-1 Program Stream + MP2 host-test fixtures.
# Requires ffmpeg with the native mpeg1video and mp2 encoders.

param(
  [string]$Ffmpeg = "ffmpeg"
)

$ErrorActionPreference = "Stop"
$Here = $PSScriptRoot

function Write-Include {
  param(
    [string]$Path,
    [string]$Symbol,
    [byte[]]$Bytes
  )

  $Builder = [System.Text.StringBuilder]::new()
  [void]$Builder.AppendLine("/* Generated by generate_media_fixtures.ps1. */")
  [void]$Builder.AppendLine("static const uint8_t ${Symbol}[] = {")
  for ($Index = 0; $Index -lt $Bytes.Length; $Index += 12) {
    $Last = [Math]::Min($Index + 12, $Bytes.Length)
    $Values = for ($ByteIndex = $Index; $ByteIndex -lt $Last; $ByteIndex++) {
      "0x{0:x2}" -f $Bytes[$ByteIndex]
    }
    [void]$Builder.Append("  ")
    [void]$Builder.Append(($Values -join ", "))
    [void]$Builder.AppendLine(",")
  }
  [void]$Builder.AppendLine("};")
  [void]$Builder.AppendLine(
    "static const uint32_t ${Symbol}_len = $($Bytes.Length)U;")
  [System.IO.File]::WriteAllText(
    $Path, $Builder.ToString(),
    [System.Text.UTF8Encoding]::new($false))
}

function New-Fixture {
  param(
    [string]$Name,
    [string]$Symbol,
    [int]$Rate,
    [int]$Channels,
    [double]$VideoDuration,
    [double]$AudioDuration,
    [double]$AudioOffset
  )

  $TempMpg = Join-Path ([System.IO.Path]::GetTempPath()) "$Name.mpg"
  try {
    & $Ffmpeg -hide_banner -loglevel error -y `
      -f lavfi -i "testsrc2=size=32x16:rate=25:duration=$VideoDuration" `
      -itsoffset $AudioOffset -f lavfi `
      -i "sine=frequency=997:sample_rate=${Rate}:duration=$AudioDuration" `
      -map 0:v -map 1:a -c:v mpeg1video -pix_fmt yuv420p `
      -g 6 -bf 2 -q:v 4 -c:a mp2 -b:a 96k -ac $Channels -ar $Rate `
      -muxdelay 0 -muxpreload 0 -f mpeg $TempMpg
    if ($LASTEXITCODE -ne 0) {
      throw "ffmpeg failed with exit code $LASTEXITCODE"
    }
    Write-Include `
      -Path (Join-Path $Here "$Name.inc") `
      -Symbol $Symbol `
      -Bytes ([System.IO.File]::ReadAllBytes($TempMpg))
  } finally {
    if ([System.IO.File]::Exists($TempMpg)) {
      [System.IO.File]::Delete($TempMpg)
    }
  }
}

New-Fixture `
  -Name "mpeg1_mp2_ps_fixture" `
  -Symbol "zz9k_mpeg1_mp2_ps_fixture" `
  -Rate 44100 -Channels 2 `
  -VideoDuration 0.48 -AudioDuration 0.40 -AudioOffset 0.08
New-Fixture `
  -Name "mpeg1_mp2_mono32_ps_fixture" `
  -Symbol "zz9k_mpeg1_mp2_mono32_ps_fixture" `
  -Rate 32000 -Channels 1 `
  -VideoDuration 0.24 -AudioDuration 0.16 -AudioOffset 0.04
New-Fixture `
  -Name "mpeg1_mp2_stereo48_ps_fixture" `
  -Symbol "zz9k_mpeg1_mp2_stereo48_ps_fixture" `
  -Rate 48000 -Channels 2 `
  -VideoDuration 0.24 -AudioDuration 0.16 -AudioOffset 0.04
