#!/usr/bin/env python3
"""Generate the ZZ9000AX audio conversion coefficient tables.

Design (see docs/plans/2026-08-21-1953-feat-qualified-48khz-audio-conversion-plan.md
KTD1-KTD3): windowed-sinc polyphase FIR, one bank per rate-pair direction,
direct phase tables committed as const Q15 arrays.

  * passband edge  fp  = 0.45 * min(in_rate, out_rate)
  * stopband edge  fst = min(in_rate, out_rate) / 2   (stop-band starts at
    the min-rate Nyquist: a wider edge such as min_rate - fp lets the
    sampled kernel's periodic replica passband land inside the real signal
    band for near-unity ratios such as 44.1k <-> 48k)
  * Kaiser window, A = 80 dB stop-band attenuation
  * exact-rational phase stepping q/p = in_rate/out_rate (reduced)
  * causal kernel: y[n] = sum_k c[phase][k] * x[base - k], group delay
    (taps-1)/2 input samples, published per rate

Codegen-time assertions (fail the build, never the target):
  * per-phase DC tap sum is exactly 16384 (unity gain, Q14)
  * per-phase L1 norm <= 48000 (int32 accumulator cannot overflow:
    32767 * 48000 = 1,572,816,000, 27% headroom under 2^31-1)

Regenerate:  python util/gen_audio_convert_tables.py
"""

import math
import os
import sys
from fractions import Fraction

RATES = [8000, 12000, 24000, 32000, 44100]
MASTER = 48000
ATTEN_DB = 80.0
PASSBAND_FACTOR = 0.45
Q14 = 1 << 14
# Unity-DC kernels are stored in Q14 (tap sum == 16384, round-shift 16 at
# runtime): a Q15 kernel's worst-case accumulator (32767 * L1) can exceed
# int32 on the long dense-ratio branches, while Q14 keeps it below
# 32767 * 48000 = 1,572,816,000, 27% headroom. Half an LSB of
# coefficient resolution is far below the 80 dB target floor.
L1_LIMIT = 48000


def sinc(x):
    """Normalized sinc: sin(pi*x) / (pi*x), sinc(0) = 1."""
    if x == 0.0:
        return 1.0
    return math.sin(math.pi * x) / (math.pi * x)


HEADER = """/*
 * Generated by util/gen_audio_convert_tables.py -- DO NOT EDIT.
 *
 * Regenerate with: python util/gen_audio_convert_tables.py
 * Design: Kaiser windowed-sinc polyphase FIR, A = {atten:g} dB,
 *         passband edge {pbf} * min(fs_in, fs_out), stopband edge
 *         min(fs_in, fs_out) - passband edge, causal delayed-symmetric
 *         kernel, exact-rational phase stepping, unity DC gain per phase
 *         (Q14 tap sum == 16384, runtime round-shift 16), per-phase L1 <= {l1}.
 */
"""

COPYRIGHT = """/*
 * ZZ9000AX audio conversion coefficient tables.
 *
 * Copyright (C) 2026, Dimitris Panokostas <midwan@gmail.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
"""




def kaiser_beta(atten_db):
    if atten_db > 50.0:
        return 0.1102 * (atten_db - 8.7)
    if atten_db >= 21.0:
        return 0.5842 * (atten_db - 21.0) ** 0.4 + 0.07886 * (atten_db - 21.0)
    return 0.0




def bessel_i0(x):
    """Modified Bessel function of the first kind, order 0 (series)."""
    total = 1.0
    term = 1.0
    k = 0
    while True:
        k += 1
        term *= (x / (2.0 * k)) ** 2
        total += term
        if term < 1e-18 * total or k > 200:
            return total


def design_direction(in_rate, out_rate):
    """Design one conversion direction; returns dict with quantized phases."""
    frac = Fraction(in_rate, out_rate)
    q, p = frac.numerator, frac.denominator
    lo = min(in_rate, out_rate)
    fp = PASSBAND_FACTOR * lo  # -0.1 dB passband edge
    fst = lo / 2.0             # stop-band edge at min-rate Nyquist
    # The -6 dB sinc cutoff sits mid-transition so the response is still
    # within ripple spec at fp and fully attenuated by fst.
    fc = (fp + fst) / 2.0
    delta_f = fst - fp
    delta_w = 2.0 * math.pi * delta_f / in_rate
    taps = int(math.ceil((ATTEN_DB - 7.95) / (2.285 * delta_w)))
    if taps < 4:
        taps = 4
    beta = kaiser_beta(ATTEN_DB)

    fc_norm = fc / in_rate  # cycles per input sample
    center = (taps - 1) / 2.0

    phases = []
    for phase in range(p):
        # c[k] addresses input position offset (k + phase/p) relative to
        # the current output position; symmetric around `center`.
        raw = []
        for k in range(taps):
            tau = k + phase / p - center
            ideal = 2.0 * fc_norm * sinc(2.0 * fc_norm * tau)
            win = bessel_i0(beta * math.sqrt(max(0.0, 1.0 - (2.0 * k / (taps - 1) - 1.0) ** 2))) / bessel_i0(beta) if taps > 1 else 1.0
            raw.append(ideal * win)
        # Normalize for unity DC gain, quantize to Q15, then repair the tap
        # sum to exactly Q15 by nudging the largest-magnitude taps.
        dc = sum(raw)
        if dc <= 0.0:
            raise SystemExit("phase %d: non-positive DC gain" % phase)
        taps_q = [int(round(c / dc * Q14)) for c in raw]
        diff = Q14 - sum(taps_q)
        order_by_mag = sorted(range(taps), key=lambda i: -abs(taps_q[i]))
        i = 0
        while diff != 0:
            idx = order_by_mag[i % taps]
            step = 1 if diff > 0 else -1
            taps_q[idx] += step
            diff -= step
            i += 1
        l1 = sum(abs(v) for v in taps_q)
        if l1 > L1_LIMIT:
            raise SystemExit(
                "phase %d: L1 %d exceeds accumulator-safety limit %d"
                % (phase, l1, L1_LIMIT)
            )
        if sum(taps_q) != Q14:
            raise SystemExit("phase %d: tap sum %d != %d" % (phase, sum(taps_q), Q14))
        phases.append(taps_q)

    return {
        "in_rate": in_rate,
        "out_rate": out_rate,
        "q": q,
        "p": p,
        "taps": taps,
        "phases": p,
        "group_delay": (taps - 1) // 2,
        "coefs": phases,
        "l1_max": max(sum(abs(v) for v in ph) for ph in phases),
    }


def c_name(direction):
    return "zz_audio_convert_ratio_%d_%d" % (
        direction["in_rate"],
        direction["out_rate"],
    )


def emit_table(direction):
    name = c_name(direction)
    lines = []
    for phase in range(direction["phases"]):
        vals = direction["coefs"][phase]
        lines.append("static const int16_t %s_p%d[%d] = {" % (name, phase, direction["taps"]))
        for start in range(0, len(vals), 12):
            chunk = ", ".join("%6d" % v for v in vals[start:start + 12])
            lines.append("\t" + chunk + ",")
        lines.append("};")
    phase_ptrs = ", ".join(
        "%s_p%d" % (name, phase) for phase in range(direction["phases"])
    )
    lines.append("")
    lines.append("const struct zz_audio_convert_ratio %s = {" % name)
    lines.append("\t.phases = %dU," % direction["phases"])
    lines.append("\t.taps = %dU," % direction["taps"])
    lines.append("\t.step_int = %dU," % (direction["q"] // direction["p"]))
    lines.append("\t.step_num = %dU," % (direction["q"] % direction["p"]))
    lines.append("\t.step_den = %dU," % direction["p"])
    lines.append("\t.group_delay = %dU," % direction["group_delay"])
    lines.append("\t.coefs = (const int16_t * const []){ %s }," % phase_ptrs)
    lines.append("};")
    return "\n".join(lines)


def main():
    src_dir = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        os.pardir, "ZZ9000_proto.sdk", "ZZ9000OS", "src",
    )
    src_dir = os.path.normpath(src_dir)

    directions = []
    for rate in RATES:
        directions.append(design_direction(rate, MASTER))  # playback
        directions.append(design_direction(MASTER, rate))  # capture
    directions.sort(key=lambda d: (d["in_rate"], d["out_rate"]))

    tables_h = os.path.join(src_dir, "audio_convert_tables.h")
    tables_c = os.path.join(src_dir, "audio_convert_tables.c")

    with open(tables_h, "w", newline="\n") as f:
        f.write(HEADER.format(atten=ATTEN_DB, pbf=PASSBAND_FACTOR, l1=L1_LIMIT))
        f.write("\n#ifndef ZZ_AUDIO_CONVERT_TABLES_H\n")
        f.write("#define ZZ_AUDIO_CONVERT_TABLES_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* One conversion direction: exact-rational step q/p =\n")
        f.write(" * in_rate/out_rate (reduced). Output n uses input base\n")
        f.write(" * (n*q)/p and phase (n*q)%p; y[n] = sum_k coefs[phase][k] *\n")
        f.write(" * x[base - k]. group_delay is in input samples.\n")
        f.write(" */\n")
        f.write("struct zz_audio_convert_ratio {\n")
        f.write("\tuint16_t phases;\n")
        f.write("\tuint16_t taps;\n")
        f.write("\tuint16_t step_int;\n")
        f.write("\tuint16_t step_num;\n")
        f.write("\tuint16_t step_den;\n")
        f.write("\tuint16_t group_delay;\n")
        f.write("\tconst int16_t *const *coefs;\n")
        f.write("};\n\n")
        for d in directions:
            f.write(
                "extern const struct zz_audio_convert_ratio %s; /* %d -> %d Hz */\n"
                % (c_name(d), d["in_rate"], d["out_rate"])
            )
        f.write("\n#endif /* ZZ_AUDIO_CONVERT_TABLES_H */\n")

    with open(tables_c, "w", newline="\n") as f:
        f.write(HEADER.format(atten=ATTEN_DB, pbf=PASSBAND_FACTOR, l1=L1_LIMIT))
        f.write(COPYRIGHT.rstrip("\n") + "\n\n")
        f.write("#include \"audio_convert_tables.h\"\n\n")
        for d in directions:
            f.write(emit_table(d))
            f.write("\n\n")

    sys.stderr.write(
        "wrote %s, %s\n" % (tables_h, tables_c)
    )
    for d in directions:
        sys.stderr.write(
            "  %5d -> %5d Hz: %3d phases x %3d taps, group delay %d input samples, max L1 %d\n"
            % (d["in_rate"], d["out_rate"], d["phases"], d["taps"],
               d["group_delay"], d["l1_max"])
        )


if __name__ == "__main__":
    main()
