#!/bin/bash
# Copyright (C) 2026, Dimitris Panokostas <midwan@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Vendor (or verify) the generated PS7 init code for the FSBL from the
# current Vivado build.
#
# ps7_init_gpl.c/h are regenerated by every bitstream build inside
#   ZZ9000_proto/ZZ9000_proto.runs/impl_1/zz9000_ps_wrapper.sysdef
# (a zip). They encode the PS register setup (clocks, DDR, MIO, AFI bus
# widths, ...) that the FSBL programs at boot, and MUST match the PS
# configuration (PCW_*) of the bitstream being shipped. A stale copy is
# exactly the failure that corrupted the 64-bit scanout DMA (stale FSBL
# kept AFI0 in 32-bit mode). See ZZ9000_proto.sdk/ZZ9000FSBL/README.md.
#
# Usage:
#   util/refresh_ps7_init.sh           extract from sysdef into FSBL src
#   util/refresh_ps7_init.sh --check   verify vendored copies match sysdef
#
# --check exits 0 with a note when no sysdef exists — a fresh clone has
# nothing to compare against. When a sysdef IS present it fails closed:
# exit 1 if the sysdef disagrees with the vendored files (PS config
# drift) or if unzip is unavailable to perform the comparison.

set -euo pipefail
cd "$(dirname "$0")/.."

SYSDEF=ZZ9000_proto/ZZ9000_proto.runs/impl_1/zz9000_ps_wrapper.sysdef
DEST=ZZ9000_proto.sdk/ZZ9000FSBL/src
FILES=(ps7_init_gpl.c ps7_init_gpl.h)

MODE=refresh
if [ "${1:-}" = "--check" ]; then
    MODE=check
fi

if [ ! -f "$SYSDEF" ]; then
    if [ "$MODE" = check ]; then
        echo "[ps7-init] no sysdef present (no local bitstream build); skipping freshness check."
        exit 0
    fi
    echo "ERROR: $SYSDEF not found — run a bitstream build first (see BUILD.md)." >&2
    exit 1
fi

# A sysdef exists, so there is something to verify against: fail closed
# if we cannot extract from it (a skipped check here is exactly the
# stale-ps7_init drift this gate exists to catch).
if ! command -v unzip >/dev/null 2>&1; then
    echo "ERROR: $SYSDEF is present but unzip is unavailable — cannot verify" >&2
    echo "       the vendored ps7_init against it. Install unzip and retry." >&2
    exit 1
fi

# Vivado emits ps7_init with environment-dependent line endings (a fresh
# %APPDATA%\Xilinx flipped this box from LF to CRLF with identical content),
# so vendored copies are normalized to LF and compared EOL-insensitively.
status=0
for f in "${FILES[@]}"; do
    if [ "$MODE" = check ]; then
        if ! unzip -p "$SYSDEF" "$f" | tr -d '\r' | cmp -s - "$DEST/$f"; then
            echo "ERROR: $DEST/$f does not match the sysdef copy." >&2
            status=1
        fi
    else
        unzip -p "$SYSDEF" "$f" | tr -d '\r' > "$DEST/$f"
        echo "[ps7-init] refreshed $DEST/$f"
    fi
done

if [ "$MODE" = check ]; then
    if [ "$status" -ne 0 ]; then
        cat >&2 <<'EOF'
The PS configuration has drifted from the vendored ps7_init code.
Run util/refresh_ps7_init.sh, rebuild the FSBL, and revalidate the
register tables (ZZ9000_proto.sdk/ZZ9000FSBL/README.md) before shipping.
EOF
        exit 1
    fi
    echo "[ps7-init] vendored ps7_init matches sysdef."
fi

exit 0
