#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Regenerate flac_fixtures.h. Encoder and reference decoder are the reference
# `flac` tool; the committed header records the exact version used. Input PCM
# is a deterministic synthetic signal (no external audio). Reference PCM is
# flac's own raw decode: signed, big-endian, ceil(bits/8) bytes per sample.
set -euo pipefail
cd "$(dirname "$0")"
command -v flac >/dev/null || { echo "flac tool required" >&2; exit 1; }
python3 - "$(flac --version)" <<'PY'
import math, struct, subprocess, sys, os, tempfile

version = sys.argv[1]
tmp = tempfile.mkdtemp()

def pcm(frames, channels, bits, seed):
    out = bytearray()
    width = (bits + 7) // 8
    peak = (1 << (bits - 1)) - 1
    x = seed
    for i in range(frames):
        for c in range(channels):
            x = (x * 1103515245 + 12345) & 0x7fffffff
            noise = (x >> 8) % 64 - 32
            v = int(peak * 0.7 * math.sin(2 * math.pi * (220 + 110 * c) * i / 8000.0)) + noise
            if i == 3:
                v = peak
            if i == 5:
                v = -peak - 1
            v = max(-peak - 1, min(peak, v))
            out += (v & ((1 << (8 * width)) - 1)).to_bytes(width, 'big')
    return bytes(out)

def run(args, data=None):
    return subprocess.run(args, input=data, stdout=subprocess.PIPE,
                          stderr=subprocess.DEVNULL, check=True).stdout

def encode(name, frames, channels, bits, rate, extra=(), stream=False, ogg=False):
    raw = pcm(frames, channels, bits, len(name))
    base = ['flac', '-s', '--force-raw-format', '--endian=big', '--sign=signed',
            '--channels=%d' % channels, '--bps=%d' % bits,
            '--sample-rate=%d' % rate, '-b', '1152'] + list(extra)
    if ogg:
        base.append('--ogg')
    if stream:
        enc = run(base + ['-c', '-'], raw)          # stdout: STREAMINFO total stays 0
    else:
        path = os.path.join(tmp, name + ('.oga' if ogg else '.flac'))
        run(base + ['-f', '-o', path, '-'], raw)
        enc = open(path, 'rb').read()
    ref = b''
    if not ogg:
        ref = run(['flac', '-s', '-d', '-c', '--force-raw-format', '--endian=big',
                   '--sign=signed', '-'], enc)
        assert ref == raw, name
    return enc, ref

fixtures = [
    ('mono8',     2000, 1,  8, 22050, ()),
    ('stereo16',  3000, 2, 16, 44100, ('-T', 'TITLE=zz9000', '--padding=300')),
    ('stereo24u', 2500, 2, 24, 48000, ()),
    ('mono24',    1800, 1, 24, 96000, ()),
]
lines = ['/* Generated by gen_fixtures.sh with %s (encoder and reference decoder).' % version,
         ' * Do not edit. SPDX-License-Identifier: GPL-3.0-or-later */',
         '#ifndef FLAC_FIXTURES_H', '#define FLAC_FIXTURES_H', '#include <stdint.h>']

def arr(name, data):
    lines.append('static const uint8_t %s[%d] = {' % (name, max(1, len(data))))
    for i in range(0, len(data), 16):
        lines.append('  ' + ', '.join('0x%02x' % b for b in data[i:i+16]) + ',')
    if not data:
        lines.append('  0')
    lines.append('};')

table = []
for name, frames, ch, bits, rate, extra in fixtures:
    enc, ref = encode(name, frames, ch, bits, rate, extra, stream=name.endswith('u'))
    arr('fx_%s_flac' % name, enc)
    arr('fx_%s_ref' % name, ref)
    table.append((name, frames, ch, bits, rate))
enc, _ = encode('multi3', 600, 3, 16, 44100, ())
arr('fx_multi3_flac', enc)
enc, _ = encode('ogg16', 600, 2, 16, 44100, (), ogg=True)
arr('fx_ogg16_flac', enc)

lines.append('struct flac_fixture { const char *name; const uint8_t *flac; uint32_t flac_len;'
             ' const uint8_t *ref; uint32_t ref_len; uint32_t frames, channels, bits, rate; };')
lines.append('static const struct flac_fixture flac_fixtures[] = {')
for name, frames, ch, bits, rate in table:
    lines.append('  { "%s", fx_%s_flac, sizeof(fx_%s_flac), fx_%s_ref, sizeof(fx_%s_ref), %d, %d, %d, %d },'
                 % (name, name, name, name, name, frames, ch, bits, rate))
lines.append('};')
lines.append('#endif')
open('flac_fixtures.h', 'w').write('\n'.join(lines) + '\n')
PY
echo "wrote flac_fixtures.h"
