/* Generated by gen_fixtures.sh. Do not edit.
 * Encoder: ffmpeg version 7.1.5-0+deb13u1 with libvorbis 1.3.7-3 (-c:a libvorbis).
 * Reference: the same ffmpeg's native floating-point Vorbis decoder,
 * converted to s16be by libswresample.
 * SPDX-License-Identifier: GPL-3.0-or-later */
#ifndef VORBIS_FIXTURES_H
#define VORBIS_FIXTURES_H
#include <stdint.h>
struct vorbis_fixture { const char *name; const char *ref; uint32_t frames, channels, rate, block0, block1, setup_bytes; };
static const struct vorbis_fixture vorbis_fixtures[] = {
  { "mono8k", "mono8k", 4000, 1, 8000, 512, 512, 2476 },
  { "mono22k", "mono22k", 8820, 1, 22050, 512, 1024, 3257 },
  { "stereo44k", "stereo44k", 22050, 2, 44100, 256, 2048, 3832 },
  { "stereo48k_q10", "stereo48k_q10", 14400, 2, 48000, 256, 2048, 3908 },
  { "stereo44k_split", "stereo44k", 22050, 2, 44100, 256, 2048, 3832 },
  { "stereo44k_bigcomment", "stereo44k", 22050, 2, 44100, 256, 2048, 3832 },
  { "stereo44k_trailing", "stereo44k", 22050, 2, 44100, 256, 2048, 3832 },
};
#endif
